name: Java Appium Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up JDK 11 for Java
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Install dependencies (Maven or Gradle can be added as per your project)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    # Build the project (change to `gradle build` if using Gradle)
    - name: Build with Maven
      run: mvn clean install

    # Run tests with Maven (use gradle test if using Gradle)
    - name: Run tests
      run: mvn test

  # Run the appium tests (Python-based appium testing in your case)
  appium-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python environment for Appium testing
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies for Appium tests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Appium tests
    - name: Run Appium tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

